/*
 * Automatically generated by jrpcgen 1.0.7 on 18/1/15 1:59 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class LINKEDLIST implements XdrAble {
    public transaction txn;
    public LINKEDLIST next;

    public LINKEDLIST() {
    }

    public LINKEDLIST(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        LINKEDLIST $this = this;
        do {
            $this.txn.xdrEncode(xdr);
            $this = $this.next;
            xdr.xdrEncodeBoolean($this != null);
        } while ( $this != null );
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        LINKEDLIST $this = this;
        LINKEDLIST $next;
        do {
            $this.txn = new transaction(xdr);
            $next = xdr.xdrDecodeBoolean() ? new LINKEDLIST() : null;
            $this.next = $next;
            $this = $next;
        } while ( $this != null );
    }

}
// End of LINKEDLIST.java
