/*
 * Automatically generated by jrpcgen 1.0.7 on 17/1/15 1:57 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

public class transaction_return implements XdrAble {
    public set_balance_return src_account;
    public set_balance_return dst_account;

    public transaction_return() {
    }

    public transaction_return(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        src_account.xdrEncode(xdr);
        dst_account.xdrEncode(xdr);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        src_account = new set_balance_return(xdr);
        dst_account = new set_balance_return(xdr);
    }

}
// End of transaction_return.java
